# Site settings
title: Milen Pivchev
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Milen Pivchev
user_title: Software Developer
email: milen.pivchev@gmail.com

linkedin_username: milen-pivchev
github_username: mpivchev

exclude: ['package.json', 'src' , 'node_modules']
